const API='http://localhost/api/browser-extension';
// A retained result may miss research targets; it is still a terminal state.
const copy={es:{title:'Página accesible',subtitle:'Remediación A11yResearch bajo demanda',language:'Idioma',theme:'Tema',themeLight:'Claro',themeDark:'Oscuro',themeSystem:'Sistema',currentPage:'Página actual',modelStrategy:'Estrategia de modelos',accessibilityPreservation:'Accesibilidad y preservación',optionalEvidence:'Evidencia opcional',selectedConfiguration:'Configuración utilizada',noOptionalEvidence:'Sin evidencia adicional',useRag:'Usar ACT RAG adaptativo',useWave:'Agregar WAVE AIM',create:'Crear versión accesible',thinking:'La IA está trabajando',thinkingDetail:'Analiza, razona y prepara una versión accesible.',anotherPage:'Nueva evaluación',applied:'La versión accesible se aplicó en esta pestaña.',applying:'Aplicando la versión accesible en la pestaña…',applyFailed:'El candidato terminó, pero no fue posible aplicarlo en esta pestaña.',unsupported:'Esta página no se puede remediar',unsupportedHelp:'Abre un sitio web con dirección http:// o https:// y vuelve a pulsar el icono.',requestFailed:'No fue posible iniciar la remediación',stages:{acquire:'Adquirir',transform:'Transformar',prompt:'Prompt',generate:'Generar',evaluate:'Evaluar',complete:'Completado'}},en:{title:'Accessible page',subtitle:'A11yResearch remediation on demand',language:'Language',theme:'Theme',themeLight:'Light',themeDark:'Dark',themeSystem:'System',currentPage:'Current page',modelStrategy:'Model strategy',accessibilityPreservation:'Accessibility and preservation',optionalEvidence:'Optional evidence',selectedConfiguration:'Configuration used',noOptionalEvidence:'No additional evidence',useRag:'Use adaptive ACT RAG',useWave:'Add WAVE AIM',create:'Create accessible version',thinking:'AI is working',thinkingDetail:'Analyzing, reasoning, and preparing an accessible version.',anotherPage:'New evaluation',applied:'The accessible version was applied to this tab.',applying:'Applying the accessible version to the tab…',applyFailed:'The candidate finished, but it could not be applied to this tab.',unsupported:'This page cannot be remediated',unsupportedHelp:'Open a website with an http:// or https:// address and click the icon again.',requestFailed:'The remediation could not be started',stages:{acquire:'Acquire',transform:'Transform',prompt:'Prompt',generate:'Generate',evaluate:'Evaluate',complete:'Complete'}}};
Object.assign(copy.es.stages,{queued:'En cola',accepted:'Aceptada',failed:'Error',metrics_not_achieved:'Umbrales no alcanzados',review_not_achieved:'Revisión no superada'});
Object.assign(copy.en.stages,{queued:'Queued',accepted:'Accepted',failed:'Error',metrics_not_achieved:'Thresholds not achieved',review_not_achieved:'Review not passed'});
copy.es.stages.completed_with_warnings='Completada con advertencias';
copy.en.stages.completed_with_warnings='Completed with warnings';
Object.assign(copy.es,{resultScores:'Mediciones de accesibilidad',measure:'Medida',original:'Original',final:'Final',target:'Objetivo',axeIssues:'Instancias Axe',scoresHelp:'Final corresponde al candidato retenido. — indica una medición no disponible.',viewReport:'Ver reporte completo ↗',reuseResults:'Usar resultados guardados'});
Object.assign(copy.en,{resultScores:'Accessibility measurements',measure:'Measure',original:'Original',final:'Final',target:'Target',axeIssues:'Axe instances',scoresHelp:'Final refers to the retained candidate. — means a measurement is unavailable.',viewReport:'View full report ↗',reuseResults:'Use stored results'});
Object.assign(copy.es,{settings:'Configuración',storedResultsTitle:'Reutilización de resultados'});
Object.assign(copy.en,{settings:'Settings',storedResultsTitle:'Stored-result reuse'});
let completionResult=null,candidateView=null;
copy.es.returnOriginal='Volver al sitio original';copy.en.returnOriginal='Return to original website';
async function restoreCompletion(item,requestId){try{const restored=await extensionResults.restore(item,item.requestId||requestId,fetch,API);if(completionResult===item){renderCompletion(restored);if(restored!==item)await chrome.storage.local.set({lastCompletion:restored})}}catch{/* Stored completion remains visible while the local backend is unavailable. */}}
let activeUrl='',activeTabId=null,timer=null,locale='es',injected=false,running=false,completionPending=false,applyingCandidate=false,runConfig=null;const $=id=>document.getElementById(id);
function applyTheme(value){const resolved=value==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value;document.documentElement.dataset.theme=resolved;const paths={light:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',dark:'<path d="M20 14A9 9 0 0 1 10 3a9 9 0 1 0 10 11Z"/>',system:'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8m-4-4v4"/>'};$('themeIcon').innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true">'+paths[value]+'</svg>'}
copy.es.subtitle='Remediación A11yResearch bajo demanda'; copy.en.subtitle='A11yResearch remediation on demand';
copy.es.modelStrategy='Modelo y razonamiento'; copy.en.modelStrategy='Model and reasoning';
function paint(){const p=+$('preservationLevel').value;$('preservationStep').value=`${p+1} / 5`;extensionControls.paint(locale,+$('modelLevel').value,p);$('captureScope').textContent=locale==='es'?'Se adquiere la URL mediante la plataforma; no se captura la sesión ni el DOM actual de esta pestaña.':'The platform acquires this URL; it does not capture this tab’s session or current DOM.'}
function translate(){const t=copy[locale];$('preferencesButton').setAttribute('aria-label',t.settings);$('preferencesButton').title=t.settings;$('language').setAttribute('aria-label',t.language);$('theme').setAttribute('aria-label',t.theme);$('theme').title=t.theme;document.documentElement.lang=locale;document.querySelectorAll('[data-i18n]').forEach(n=>n.textContent=t[n.dataset.i18n]);document.querySelectorAll('[data-stage]').forEach(n=>n.textContent=t.stages[n.dataset.stage]);paint();if(!$('completionSummary').hidden)paintCompletion()}
function resetProgress(){clearTimeout(timer);timer=null;$('returnOriginal').hidden=true;injected=false;running=false;completionPending=false;applyingCandidate=false;runConfig=null;completionResult=null;$('completionScores').hidden=true;chrome.storage.local.remove(['activeRequestId','runTabId','runUrl','runConfig','runReused','lastCompletion']);$('runForm').hidden=false;$('progress').hidden=true;$('progress').classList.remove('finished');delete $('phase').dataset.state;$('completionSummary').hidden=true;$('newPage').hidden=true;$('error').hidden=true;$('bar').style.width='0%';$('percent').textContent='0%';$('message').textContent='';$('start').disabled=false}
function readActiveTab(reset=false){chrome.tabs.query({active:true,lastFocusedWindow:true},tabs=>{const tab=tabs[0],nextUrl=extensionResults.sourceUrl(tab,candidateView);if(reset||nextUrl!==activeUrl)resetProgress();activeTabId=tab?.id??null;activeUrl=nextUrl;try{const u=new URL(activeUrl);if(!['http:','https:'].includes(u.protocol))throw new Error();$('pageHost').textContent=u.hostname;$('pageUrl').textContent=activeUrl;$('start').disabled=false}catch{$('pageHost').textContent=copy[locale].unsupported;$('pageUrl').textContent=copy[locale].unsupportedHelp;$('start').disabled=true}})}
function rememberCompletion(message,status='complete'){completionPending=true;const item={url:activeUrl,message,status,config:runConfig,finishedAt:Date.now()};chrome.storage.local.set({lastCompletion:item});chrome.storage.local.remove(['activeRequestId','runTabId','runUrl']);if(chrome.notifications)chrome.notifications.create(`warp-${item.finishedAt}`,{type:'basic',iconUrl:'icons/warp-icon-128.png',title:locale==='es'?'Remediación terminada':'Remediation finished',message})}
function renderCompletion(item){completionResult=item;if(item.tabId!=null)activeTabId=item.tabId;$('returnOriginal').hidden=!item.viewUrl;activeUrl=item.url||activeUrl;runConfig=item.config||runConfig;completionPending=true;$('runForm').hidden=true;$('progress').hidden=false;$('progress').classList.add('finished');const completionState=item.status||'complete';$('phase').textContent=copy[locale].stages[completionState]||copy[locale].stages.complete;$('phase').dataset.state=completionState;$('percent').textContent='100%';$('bar').style.width='100%';$('message').textContent=item.message||copy[locale].applied;paintCompletion();$('completionSummary').hidden=false;$('newPage').hidden=false;$('start').disabled=false;try{const u=new URL(activeUrl);$('pageHost').textContent=u.hostname;$('pageUrl').textContent=activeUrl}catch{}}
function paintCompletion(){extensionResults.paint(completionResult,locale,$);const t=copy[locale],config=runConfig||{};$('completedModel').textContent=config.modelName||config.selectedModel||'—';$('completedPreservation').textContent=config.preservationName||'—';const evidence=[];if(config.rag)evidence.push('ACT RAG');$('completedEvidence').textContent=evidence.join(' + ')||t.noOptionalEvidence}
async function recoverLatest(url,tabId){try{const response=await fetch(`${API}/requests/latest?url=${encodeURIComponent(url)}`),data=await response.json();if(!response.ok)return false;activeUrl=url;activeTabId=tabId;runConfig=runConfig||currentConfig();await chrome.storage.local.set({activeRequestId:data.id,runTabId:tabId,runUrl:url,runConfig});running=!['accepted','completed_with_warnings','failed','metrics_not_achieved','review_not_achieved'].includes(data.status);$('runForm').hidden=true;$('progress').hidden=false;$('start').disabled=true;poll(data.id);chrome.runtime.sendMessage({type:'TRACK_REMEDIATION'});return true}catch{return false}}
document.querySelectorAll('.dots').forEach(box=>{for(let i=0;i<5;i++)box.append(document.createElement('i'))});$('modelLevel').oninput=$('preservationLevel').oninput=paint;$('useRag').onchange=paint;
$('preferencesButton').onclick=()=>{const open=$('preferences').hidden;$('preferences').hidden=!open;$('preferencesButton').setAttribute('aria-expanded',String(open))};
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('preferences').hidden){$('preferences').hidden=true;$('preferencesButton').setAttribute('aria-expanded','false');$('preferencesButton').focus()}});
$('language').onchange=()=>{locale=$('language').value;chrome.storage.local.set({locale});translate();if(!running)readActiveTab()};$('theme').onchange=()=>{chrome.storage.local.set({theme:$('theme').value});applyTheme($('theme').value)};$('newPage').onclick=()=>readActiveTab(true);
chrome.tabs.onActivated.addListener(()=>{if(!running&&!completionPending)readActiveTab(true)});chrome.tabs.onUpdated.addListener((tabId,change)=>{if(tabId!==activeTabId||extensionResults.viewChange(tabId,change,candidateView))return;if(completionPending&&!applyingCandidate&&(change.url&&change.url!==activeUrl||change.status==='loading')){readActiveTab(true);return}if(change.url&&!running&&!completionPending)readActiveTab(true)});
chrome.storage.local.get({locale:'es',theme:'light',activeRequestId:null,runTabId:null,runUrl:'',runConfig:null,lastCompletion:null,completedRequestId:null,candidateView:null},prefs=>{candidateView=prefs.candidateView;locale=prefs.locale;runConfig=prefs.runConfig;$('language').value=locale;$('theme').value=prefs.theme;applyTheme(prefs.theme);translate();if(prefs.activeRequestId&&prefs.runTabId!==null&&prefs.runUrl){activeUrl=prefs.runUrl;activeTabId=prefs.runTabId;running=true;const u=new URL(activeUrl);$('pageHost').textContent=u.hostname;$('pageUrl').textContent=activeUrl;$('runForm').hidden=true;$('start').disabled=true;$('progress').hidden=false;chrome.runtime.sendMessage({type:'TRACK_REMEDIATION'});poll(prefs.activeRequestId)}else if(prefs.lastCompletion&&prefs.lastCompletion.status==='failed'&&/failed to fetch|fetch failed/i.test(prefs.lastCompletion.message||'')){chrome.tabs.query({active:true,lastFocusedWindow:true},async tabs=>{const tab=tabs[0],url=prefs.lastCompletion.url||tab?.url||'';if(!await recoverLatest(url,tab?.id??null)){await chrome.storage.local.remove('lastCompletion');readActiveTab(true)}})}else if(prefs.lastCompletion){renderCompletion(prefs.lastCompletion);restoreCompletion(prefs.lastCompletion,prefs.completedRequestId)}else readActiveTab()});
chrome.storage.onChanged.addListener((changes,area)=>{if(area!=='local')return;if(changes.candidateView)candidateView=changes.candidateView.newValue||null;if(changes.lastCompletion?.newValue){running=false;renderCompletion(changes.lastCompletion.newValue)}});
$('returnOriginal').onclick=async()=>{const item=completionResult;if(!item?.url||item.tabId==null)return;try{await extensionResults.returnOriginal(item,chrome.tabs);candidateView=null;await chrome.storage.local.remove('candidateView');readActiveTab(true)}catch(error){$('error').textContent=error.message;$('error').hidden=false}};
$('runForm').onsubmit=async e=>{e.preventDefault();if(!extensionControls.catalog)return;const config=currentConfig(),forceRerun=!$('reuseResults').checked;resetProgress();runConfig=config;running=true;$('runForm').hidden=true;$('start').disabled=true;$('progress').hidden=false;try{const response=await fetch(`${API}/requests`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:activeUrl,selected_model:config.selectedModel,preservation_level:config.preservation,use_rag:config.rag,force_rerun:forceRerun})});const data=await response.json();if(!response.ok)throw new Error(data.error||copy[locale].requestFailed);await chrome.storage.local.set({activeRequestId:data.id,runTabId:activeTabId,runUrl:activeUrl,runConfig,runReused:!!data.reused});chrome.runtime.sendMessage({type:'TRACK_REMEDIATION'});poll(data.id)}catch(error){showError(error.message)}};
async function poll(id){clearTimeout(timer);try{const response=await fetch(`${API}/requests/${id}`),data=await response.json();if(!response.ok)throw new Error(data.error||copy[locale].requestFailed);$('error').hidden=true;const key=(data.phase||data.status||'acquire').toLowerCase(),phase=$('phase');phase.textContent=copy[locale].stages[key]||key.replaceAll('_',' ');phase.dataset.state=key;$('percent').textContent=`${data.progress||0}%`;$('bar').style.width=`${data.progress||0}%`;$('message').textContent=data.message||'';const order=['acquire','transform','prompt','generate','evaluate'],current=Math.max(0,order.indexOf(key));document.querySelectorAll('#stages li').forEach((li,i)=>{li.classList.toggle('completed',i<current);li.classList.toggle('current',i===current);li.classList.toggle('pending',i>current)});if(['accepted','completed_with_warnings','failed','metrics_not_achieved','review_not_achieved'].includes(data.status)){chrome.runtime.sendMessage({type:'FINISH_REMEDIATION',requestId:id});return}timer=setTimeout(()=>poll(id),2500)}catch(error){$('error').textContent=`${error.message} · ${locale==='es'?'Reintentando…':'Retrying…'}`;$('error').hidden=false;timer=setTimeout(()=>poll(id),5000)}}
function currentConfig(){const m=extensionControls.model(+$('modelLevel').value),p=+$('preservationLevel').value;return{selectedModel:m?.id,modelName:m?.name,preservation:p,preservationName:$('preservationName').textContent,rag:$('useRag').checked,wave:false}}
extensionControls.load(API).then(()=>{paint();if(!running)$('start').disabled=!/^https?:/.test(activeUrl)}).catch(error=>{$('start').disabled=true;$('error').textContent=error.message;$('error').hidden=false});
function showError(text){clearTimeout(timer);running=false;$('progress').classList.add('finished');const network=/failed to fetch|fetch failed/i.test(text||''),message=network?(locale==='es'?'No se pudo conectar temporalmente con la plataforma local. Reintentando…':'Could not temporarily reach the local platform. Retrying…'):text;$('error').textContent=message;$('error').hidden=false;$('newPage').hidden=!network;$('start').disabled=false;if(network){timer=setTimeout(()=>recoverLatest(activeUrl,activeTabId),4000)}else rememberCompletion(message,'failed')}
